[package]
name = "jacks/newprojecttemplate"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

[server-dependencies]
profilestore = "vyon/profilestore@1.0.3"